### ISSUE TITLE
Release Notes for version 1.4.1

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig-docs#25] opened 2021-04-20 08:31 UTC
Need a user-friendly release notes for version 1.4.1, based on this changelog - https://github.com/synfig/synfig/pull/2118

See example Release notes for 1.3.15 - https://synfig.readthedocs.io/en/latest/releases/development/1.3.15.html
Source - https://github.com/synfig/synfig-docs/blob/master/source/releases/development/1.3.15.rst

Release notes for 1.4.1 should be placed here -
https://github.com/synfig/synfig-docs/tree/master/source/releases/stable

**Comment by rodolforg** [comment] 2021-04-21 03:33
I'm not good for this at all, but I can try to group them here:

### Windows issues
- fix mainwindow not showing when is offscreen (synfig/synfig#1973) [studio]  **(the bug when closing minimized app)**

#### Non-latin chars issues

- current_working_directory() function now works correctly with non-Latin filenames (synfig/synfig#2011)  [ETL]
- Fixed issue with rendering to file when using non-Latin filenames (synfig/synfig#1940) [core] [studio]
- Fixed incorrect import of lst files when path contains non-Latin characters (synfig/synfig#1924) [core]
- Fixed non-working command "Edit image editing in external tool..." (synfig/synfig#1912) [studio]
- Fixed problem with non-working plugins when using paths containing non-Latin characters (synfig/synfig#1882) [studio]
-  Merge PR synfig/synfig#1889: [Synfig Studio/Windows] Fixed load/save operations for Palette editor [core] [studio]

### Crash fixes

- avoid dereference of invalid TreeIter on Layer TreeView (synfig/synfig#2043) [studio] **(user dragging and dropping layers in tree)** (mainly on Windows)
- fix "Link to Spline" showing when a vertex of spline itself is selected (synfig/synfig#1988) [studio]
- Fixed crash when right-clicking on group in the Sets panel (synfig/synfig#1920) [studio]
- Fix crash in Spline Tangent converter (synfig/synfig#1836) [core]
- Fix crash in Spline Vertex converter (https://github.com/synfig/synfig/issues/1731) [core]
- Fix crash on unsuccessful action with a clean undo history (synfig/synfig#1643) [studio]
- Merge PR synfig/synfig#1861: Fixed crash when frame rendering throws exception while animating [studio]

### Regression fixes

- Merge PR synfig/synfig#1971: Fix action LayerDuplicate with layers "duplicate" [studio]
- fix Duplicate layer ignoring all layers but the first one (synfig/synfig#1829) [core]
- Restore ctrl-c ctrl+v ctrl+a in Color and Gradient Dialogs (synfig/synfig#1821) [studio]

### UI/UX issues

- Change order of Waypoint Editor buttons to match other dialogs (synfig/synfig#1880) [studio]
- Waypoint Editor didn't properly support enums (synfig/synfig#1968) [studio]
- Bumped year in About dialog (synfig/synfig#1977) [studio] **("irrelevant")**
- Return true only if id=1 (accept) is clicked (synfig/synfig#1573) [studio] **(Now closing some ok/cancel dialogs means 'cancel' and not 'ok')**
- Merge PR synfig/synfig#1386: Toolbar menu [studio]

### MacOS
- [MacOS] Fixed SynfigStudio.app won't start if renamed (or contain spaces in name) (synfig/synfig#1834)

### Features
- Export video files with sound (synfig/synfig#1623) [core]
(- Fixed error when output to MPEG-1 format with audio (synfig/synfig#1830) [core])

### Code cleanup/quality/organization (not relevant for regular user)
- autotools: pango and imagemagick c++ flags and libs have been moved to their respective modules (synfig/synfig#1688) [core]
- [Autotools] remove support for broken OpenGL renderering (synfig/synfig#2055) [core]
- exception-guard now lists SynfigApp exception too (synfig/synfig#2028) [studio]

### Bug fixes
- Added support for loading average values (synfig/synfig#1955) [core] **(since when this bug exists?! Was it a regression?! 1.0.2 according to related bug issue)**
- Fix animation interpolation for boolean values (synfig/synfig#1826) [core] **(I don't know if it was a regression or a long-standing bug too – 1.2.2 presented this issue too)**

### Others I don't know how to label
- don't let inner layer be duplicated twice (synfig/synfig#2050) [studio] **(behavior change to prevent crashes in the new implementation)**
- assure uniqueness for new node guid (synfig/synfig#2029) [core] **(it prevents some random crashes)**

**Comment by morevnaproject** [comment] 2021-05-05 13:30
Thank you @rodolforg! This is a very good start!

I suggest to start with new features, then regressions, crashes and bugfixes. I like the idea to have separate "UI/UX issues" section - as we have many for this release. ^__^

We can safely drop "Code cleanup/quality/organization" (you indicated that in title already), and "Bumped year in About dialog" item.

I think all items from "Non-latin chars issues" can be mentioned as single item "Fix problems of handling paths with non-latin symbols in filename ()"

Same can be done for "Export video files with sound" - we can have single item for it and list relevant PRs - https://github.com/synfig/synfig/pull/1623 and https://github.com/synfig/synfig/pull/1830

**Comment by morevnaproject** [comment] 2021-05-07 04:29
I am taking this task to prepare final release notes text. ^__^

**Comment by morevnaproject** [comment] 2021-05-09 03:56
OK, I end up with a bit different structure in #28 ^__^"

**Closed** 2021-05-09 04:21 UTC
